apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kqv3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ufhk-tenant/rhtap-demo-app/hacbs-test-project-kqv3@sha256:2864705d10e7f927c8c5d803797ba3c2fa2b51c47bdabdacf6175185012bae8d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
