apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kqv3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ufhk-tenant/rhtap-demo-app/hacbs-test-project-kqv3@sha256:05f29958ca8ae3107e2e45c029762f28dffc9a486b9f02940752927d1790296b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
